### ISSUE TITLE
BAG Full Extract V2 is loaded once in bigquery

### ISSUE THREAD

**Issue by galamit86** [dataverbinders/toepol#3]
[This](https://www.kadaster.nl/-/kosteloze-download-bag-2.0-extract) single extract of the BAG registry should be uploaded a single time into bigquery (that will serve as the basis for a recurring processing of mutations).

Eddy's Code [here](https://github.com/dataverbinders/nl-open-data/tree/issue-1-BAG_data_is_ingeladen/nl_open_data/flows/kadaster) could possibly be reused.

### Todo (rough)
- [ ] Load a single row
- [ ] Load a single file
- [ ] load a folder
- [ ] load a different folder
- [ ] load all folders

**Comment by eddyVintus** [comment]
**Update:**
 - Managed to upload multiple files into GBQ. 
   - Using my old script [test_prefect_bag.py](https://github.com/dataverbinders/toepol/blob/bag_etl/kadaster/test_prefect_bag.py) which is now in this [branch](https://github.com/dataverbinders/toepol/tree/bag_etl/kadaster) in the kadaster folder.
     - Need improvements, i.e. uses the old config file
   - As discussed, first let GBQ decide the datatypes which gave an error since GBQ thinks the datatype for a field has changed.
 - On the Developer Kadaster website I found the [schemas](https://developer.kadaster.nl/schemas/-/categories/4119958) which are referenced in [Koppelvlak BAG 2.0 Extract](https://www.kadaster.nl/documents/1953498/2762071/BAG+2.0+Extract+koppelvlak.pdf/81c56965-492b-6525-007a-f264a76f9e7d?t=1633441344565).
   - Inside the ZIP are multiple xsd files 
     - In _IMBAGLV_Objecten-2.1.0.xsd_ some datatypes are defined for the attributes of a BAG object.
     - Was able to upload files for _Woonplaats_ and _Nummeraanduiding_ in GBQ by updating [bag_schemas.py](https://github.com/dataverbinders/toepol/blob/bag_etl/kadaster/bag_schemas.py) using the above file.
     - Compared the datatypes defined for _Woonplaats_ and _Nummeraanduiding_ in _IMBAGLV_Objecten-2.1.0.xsd_ and _datafundament-logical.dbs_ and there are some small differences.

**Comment by galamit86** [comment]
@eddyVintus - gret, summary, thanks!

I propose our next step could be writing a simple general parser translating `IMBAGLV_Objecten-2.1.0.xsd` to something like your `bag_schemas.py`. Any thoughts? Have you had something else in mind to go forward?

@JeremyVintus @dkapitan - Any input?

**Comment by eddyVintus** [comment]
**Update:**

- Based on functions in [test_dataproc.py](https://github.com/dataverbinders/toepol/blob/bag_etl/kadaster/test_dataproc.py) tried to wrap them as Prefect Tasks in [test_pyspark.py](https://github.com/dataverbinders/toepol/blob/bag_etl/kadaster/test_pyspark.py) for local testing.
- Was able to write the DF's to a snappy.parquet?? file.
- Still have to upload these files to GCS, now used a rough approach using [Cloud Storage API](https://cloud.google.com/storage/docs/uploading-objects#storage-upload-object-code-sample).

**Comment by MarcZoon** [comment]
Using the bag2gcs.py file, we can now register a flow that stores the bag objects as .parquet files on GCS.

One issue remains, for some reason the flow is unable to completely run using Prefect version 1.0.0. But it does work on version 0.15.13.

**Comment by eddyVintus** [comment]
Created Register and Run for both flows

**Comment by MarcZoon** [comment]
**Update:**

Added a new prefect flow (and files it depends on).

We can now create a Dataproc cluster from within the flow, and submit a PySpark job. Therefore, most work is now done on Dataproc, while still being managed by Prefect.

I have not had the chance to do a full load yet, but partial loads were successful, so it seems like it should work. _(knock on wood)_
